spring:
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

server:
  port: 35680

---

spring:
  profiles: local

---

spring:
  profiles: dev
