spring:
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    add-mappings: true
#    static-locations: classpath:/static/

#custom:
#  path:
#    upload: 'C:/Users/Gyu/cmmnUploadFiles/'

server:
  port: 80

---

spring:
  profiles: local
#logging:
#  config: classpath:log4j2.xml

key:
  ffmpeg:
    path: /ffmpeg/files
  ffprobe:
    path: /ffprobe/files

---

spring:
  profiles: dev
