spring:
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

server:
  port: 35680

---

spring:
  profiles: local
#logging:
#  config: classpath:log4j2.xml

key:
  ffmpeg:
    path: /ffmpeg/files
  ffprobe:
    path: /ffprobe/files

---

spring:
  profiles: dev
